// Code generated by mockery v2.45.0. DO NOT EDIT.

package workermock

import (
	context "context"

	"github.com/jmontesinos91/oevents"
	mock "github.com/stretchr/testify/mock"
)

// IWorker is an autogenerated mock type for the IWorker type
type IWorker struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, event
func (_m *IWorker) Handle(ctx context.Context, event oevents.OmniViewEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, oevents.OmniViewEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIWorker creates a new instance of IWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *IWorker {
	mock := &IWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
