// Code generated by mockery v2.50.2. DO NOT EDIT.

package logsmessagemock

import (
	context "context"

	"github.com/jmontesinos91/omnilogger/internal/repositories/log_message"

	mock "github.com/stretchr/testify/mock"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, model
func (_m *IRepository) Create(ctx context.Context, model *log_message.Model) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *log_message.Model) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, ID, filter
func (_m *IRepository) FindByID(ctx context.Context, ID *int) (*log_message.Model, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *log_message.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int) (*log_message.Model, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int) *log_message.Model); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log_message.Model)
		}
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, model
func (_m *IRepository) Update(ctx context.Context, id *int, lang string, model *log_message.Model) error {
	ret := _m.Called(ctx, id, model)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *int, string, *log_message.Model) error); ok {
		r0 = rf(ctx, id, lang, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByIDAndLang provides a mock function with given fields: ctx, ID, lang
func (_m *IRepository) FindByIDAndLang(ctx context.Context, id *int, lang string) (*log_message.Model, error) {
	ret := _m.Called(ctx, id, lang)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *log_message.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *int) (*log_message.Model, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *int) *log_message.Model); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log_message.Model)
		}
	}

	return r0, r1
}

// Retrieve provides a mock function with given fields: ctx, filter
func (_m *IRepository) Retrieve(ctx context.Context, filter log_message.Filter) ([]log_message.Model, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 []log_message.Model
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, log_message.Filter) ([]log_message.Model, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, log_message.Filter) []log_message.Model); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]log_message.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, log_message.Filter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, log_message.Filter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
